export const ENV_JWT_SECRET = "JWT_SECRET";
export const ENV_DATABASE_URL = "DATABASE_URL";
export const ENV_OPENAI_API_KEY = "OPENAI_API_KEY";
export const ENV_OPENAI_BASE_URL = "OPENAI_BASE_URL";
export const ENV_RP_ALLOWED_ORIGINS = "RP_ALLOWED_ORIGINS";
export const ENV_RP_NAME = "RP_NAME";
export const ENV_OAUTH_FRONTEND_URL = "OAUTH_FRONTEND_URL";
