export const ENV_JWT_SECRET = "JWT_SECRET";
export const ENV_DATABASE_URL = "DATABASE_URL";
export const ENV_GITHUB_CLIENT_ID = "GITHUB_CLIENT_ID";
export const ENV_GITHUB_CLIENT_SECRET = "GITHUB_CLIENT_SECRET";
export const ENV_GITHUB_OAUTH_SCOPE = "GITHUB_OAUTH_SCOPE";
export const ENV_OPENAI_API_KEY = "OPENAI_API_KEY";
export const ENV_OPENAI_BASE_URL = "OPENAI_BASE_URL";
export const ENV_RP_ALLOWED_ORIGINS = "RP_ALLOWED_ORIGINS";
export const ENV_RP_NAME = "RP_NAME";
export const ENV_APP_OTEL_EXPORTER_OTLP_METRICS_ENDPOINT =
  "APP_OTEL_EXPORTER_OTLP_METRICS_ENDPOINT";
export const ENV_APP_OTEL_EXPORTER_OTLP_HEADERS =
  "APP_OTEL_EXPORTER_OTLP_HEADERS";
export const ENV_DENO_DEPLOYMENT_ID = "DENO_DEPLOYMENT_ID";
