export const ENV_APP_BASE_URL = "APP_BASE_URL";
export const ENV_JWT_SECRET = "JWT_SECRET";
export const ENV_DATABASE_URL = "DATABASE_URL";
export const ENV_GITHUB_CLIENT_ID = "GITHUB_CLIENT_ID";
export const ENV_GITHUB_CLIENT_SECRET = "GITHUB_CLIENT_SECRET";
export const ENV_GITHUB_OAUTH_SCOPE = "GITHUB_OAUTH_SCOPE";
export const ENV_DEPLOYMENT_ENVIRONMENT = "DEPLOYMENT_ENVIRONMENT";
export const ENV_APP_OTEL_EXPORTER_OTLP_ENDPOINT =
  "APP_OTEL_EXPORTER_OTLP_ENDPOINT";
export const ENV_APP_OTEL_EXPORTER_OTLP_HEADERS =
  "APP_OTEL_EXPORTER_OTLP_HEADERS";
export const ENV_DENO_DEPLOYMENT_ID = "DENO_DEPLOYMENT_ID";
